---
title: "Coste-eficacia de PrEP en España"
author: "Philip Wikman"
date: "15 de mayo de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(parallel)
library(tidyr)
library(DirichletReg)
library(BCEA)
source("invbeta.R")
source("invgamma.R")
source("HIVSIM04.R")
source("QalyCalc.R")
source("CostCalc.R")
source("QALYCostP.R")
```

# Load best fit parameters
```{r}
load("BestParam_LCA")
```

# PSA sensitivity analysis
## Simular sin PrEP
```{r}
#MAT<-matrix(data=NA, nrow=i, ncol=2)

repeats<-50
MAT<-matrix(data=NA, nrow=repeats, ncol=2)
DistEdad<-vector(length=85)
DistEdad[1:10]<-0.114106384/10
DistEdad[11:20]<-0.116645332/10
DistEdad[21:30]<-0.281029342/10
DistEdad[31:40]<-0.30552628/10
DistEdad[41:50]<-0.112127906/10
DistEdad[51:85]<-0.070564755/35
  
Age<-85
years<-20
NoSem<-52

  
WAIDS<-0.7/52  
WHIV<-0.84/52
WM350<-0.94/52
WTREAT<-0.96/52    
WSusceptible<-1/52

Treatcost<-188.54
AIDScost<-19000/52
PrEPcost<-21.74
RiskRed<-1-0.86

Woff<-0.014/52 #Proportion of people who go off PrEP 
W<-0.089/52    #Proportion of people who go on PrEP 

PSA<-function(repeats){
for(i in 1:repeats) {

 NumHSHVIH<-rnorm(1,Bestparam[1],4000)
  NumHSH<-892955-NumHSHVIH#(INE)
  #Informe del continuo asistencial
  
  #Distribucion de los pacientes por rango de CD4
  j<-c(rnorm(1,Bestparam[2], Bestparam[2]*0.2),rnorm(1,Bestparam[3], Bestparam[3]*0.2),rnorm(1,Bestparam[4], Bestparam[4]*0.2),rnorm(1,Bestparam[5], Bestparam[5]*0.2))
  ACD4<-j[1]  #<200
  I8CD4<-j[2] #200-350
  I7CD4<-j[3] #350-500
  Rest<-j[4]  #>500
  PropTR<-invbeta(Bestparam[6],0.1)
  G<-rnorm(1,Bestparam[7], Bestparam[7]*0.2) #Population growth rate 1/1000 anually
  Woff<-0.12/52 #Proportion of people who go off PrEP 
  W<-0.3/52    #Proportion of people who go on PrEP 
  m<-read.csv("MortPobGen.csv", header=TRUE, sep=";")  #Mortality general population
  mVIH235<-rnorm(1,Bestparam[8], Bestparam[8]*0.2) #Alejos et al Medicine 2016
  mVIH35<-rnorm(1,Bestparam[9],Bestparam[9]*0.2)#Alejos et al Medicine 2016
  mAIDS<-rnorm(1,Bestparam[10],Bestparam[10]*0.2)#Parastu et al PLOSone 2018
  Cvh<-rnorm(1,Bestparam[11],Bestparam[11]*0.2) #Partner change rate in the very high group 18-123/year Nichols et al. 2016
  Ch<-rnorm(1,Bestparam[12],Bestparam[12]*0.2)     #Partner change rate in the high group 5-18/year Nichols et al. 2016
  Cl<-rnorm(1,Bestparam[13],Bestparam[13]*0.2)    #Partner change rate in the low group 0.5-5/year Nichols et al. 2016
  Cvl<-rnorm(1,Bestparam[14],Bestparam[14]*0.2)  #Partner change rate in the very low group 0.04-0.5/year Nichols et al. 2016
  
  #j1<-c(rnorm(1,Bestparam[15], Bestparam[15]*0.2),rnorm(1,Bestparam[16], Bestparam[16]*0.2),rnorm(1,Bestparam[17], Bestparam[17]*0.2),rnorm(1,Bestparam[18], Bestparam[18]*0.2))
  j1<-rdirichlet(1,c(Bestparam[15], Bestparam[16], Bestparam[17], Bestparam[18]))
  nvh<-j1[1]    #Proportion of the total population in each group 5-15% Nichols et al. 2016
  nh<-j1[2]      # previo 0.4---30-50% Nichols et al. 2016
  nl<-j1[3]      # previo 0.3---10-35% Nichols et al. 2016
  nvl<-j1[4]    # previo 0.1---4-46%
  B<-rnorm(1,Bestparam[19], Bestparam[19]*0.2)  #per partnership transmissibility Nichols et al 2016.
  I12<-invbeta(Bestparam[20],Bestparam[20]*0.2) #1 month duration in stage 1 of HIV infection
  I23<-invbeta(Bestparam[21],Bestparam[21]*0.2) #1 month duration in stage 2 of HIV infection
  I34<-invbeta(Bestparam[22],Bestparam[22]*0.2) #1 month duration in stage 3 of HIV infection
  I45<-invbeta(Bestparam[23],Bestparam[23]*0.2) #3 month duration in stage 4 of HIV infection
  I55<-invbeta(Bestparam[25],Bestparam[25]*0.2)  #3 month duration in stage 5 of HIV infection
  I56<-invbeta(Bestparam[26],Bestparam[26]*0.2)  #3 month duration in stage 6 of HIV infection
  I67<-invbeta(Bestparam[27],Bestparam[27]*0.2)  #Chronic duration in stage 7 of HIV infection
  I78<-invbeta(Bestparam[28],Bestparam[28]*0.2) #Chronic duration in stage 8 of HIV infection
  I89<-invbeta(Bestparam[29],Bestparam[29]*0.2)  #Chronic duration in stage 9 of HIV infection
  PTr<-c(invbeta(Bestparam[30],Bestparam[30]*0.2),invbeta(Bestparam[31],Bestparam[31]*0.2),invbeta(Bestparam[32],Bestparam[32]*0.2)) #Nuñez et al AIDS 2018  200-500->500

Q<-HIVSIMPREP(Age, NoSem, NumHSH, NumHSHVIH, 
          ACD4, I8CD4, I7CD4, Rest, 
          G, Woff, W, 
          m, mAIDS, mVIH235, mVIH35, mTr, 
          Cvh, Ch, Cl, Cvl, 
          nvh, nh, nl, nvl, B,
          I12, I23, I34, 
          I45, I55, 
          I56, I67, 
          I78, I89, PTr, years, PropTR)

MAT[i,]<-(QALYCostP(Q))

}

MAT
}
```
```{r}
ncores<-detectCores()
cl<-makeCluster(ncores, type="PSOCK")
clusterSetRNGStream(cl, iseed=1)
clusterExport(cl, c("MAT", "Bestparam", "DistEdad", "Age", "years", "NoSem", "RiskRed","WAIDS", "WHIV", "WM350", "WTREAT", "WSusceptible", "Treatcost", "AIDScost","QALYCostP", "invbeta", "QalyCalc", "HIVSIMPREP", "PSA", "CostCalc", "rdirichlet", "invbeta", "W", "Woff", "PrEPcost"))

MAT1<-clusterCall(cl, fun=PSA, repeats)

stopCluster(cl)
#MAT2NP<-PSA(10)
x<-vector(length=2, mode="numeric")
for (i in 1:ncores){x<-rbind(x,MAT1[[i]])}
MAT2<-as.matrix(x[-1,])
MAT2<-cbind(MAT2, "PrEP-TDF")
save(MAT2, file="MAT2")
MAT2
```


## Simular con PrEP LCA
```{r}

RiskRed<-1-0.96
DistEdad<-vector(length=85)
DistEdad[1:10]<-0.114106384/10
DistEdad[11:20]<-0.116645332/10
DistEdad[21:30]<-0.281029342/10
DistEdad[31:40]<-0.30552628/10
DistEdad[41:50]<-0.112127906/10
DistEdad[51:85]<-0.070564755/35

MATP<-matrix(data=NA, nrow=repeats, ncol=2)
  
Age<-85
years<-20
NoSem<-52

WAIDS<-0.7/52  
WHIV<-0.84/52
WM350<-0.94/52
WTREAT<-0.96/52    
WSusceptible<-1/52

Treatcost<-188.54
AIDScost<-19000/52
PrEPcost<-200
RiskRed<-1-0.96


PSAPrep<-function(repeats){
for(a in 1:repeats) {

  RiskRed<-1-0.96
  NumHSHVIH<-rnorm(1,Bestparam[1],4000)
  NumHSH<-892955-NumHSHVIH#(INE)
  #Encuesta hospitalaria
  
  #Distribucion de los pacientes por rango de CD4 
  j<-c(rnorm(1,Bestparam[2], Bestparam[2]*0.2),rnorm(1,Bestparam[3], Bestparam[3]*0.2),rnorm(1,Bestparam[4], Bestparam[4]*0.2),rnorm(1,Bestparam[5], Bestparam[5]*0.2))
  ACD4<-j[1]  #<200
  I8CD4<-j[2] #200-350
  I7CD4<-j[3] #350-500
  Rest<-j[4]  #>500
  PropTR<-invbeta(Bestparam[6],0.1)
  G<-rnorm(1,Bestparam[7], Bestparam[7]*0.2) #Population growth rate 1/1000 anually
  Woff<-1-exp(-0.12/52) #Proportion of people who go off PrEP 10% anually
  W<-1-exp(-0.3/52)    #Proportion of people who go on PrEP 30% anually
  m<-read.csv("MortPobGen.csv", header=TRUE, sep=";")  #Mortality general population
  mVIH235<-rnorm(1,Bestparam[8], Bestparam[8]*0.2) #Alejos et al Medicine 2016
  mVIH35<-rnorm(1,Bestparam[9],Bestparam[9]*0.2) #Alejos et al Medicine 2016
  mAIDS<-rnorm(1,Bestparam[10],Bestparam[10]*0.2) #Parastu et al PLOSone 2018
  Cvh<-rnorm(1,Bestparam[11],Bestparam[11]*0.2) #Partner change rate in the very high group 18-123/year Nichols et al. 2016
  Ch<-rnorm(1,Bestparam[12],Bestparam[12]*0.2) #Partner change rate in the high group 5-18/year Nichols et al. 2016
  Cl<-rnorm(1,Bestparam[13],Bestparam[13]*0.2)    #Partner change rate in the low group 0.5-5/year Nichols et al. 2016
  Cvl<-rnorm(1,Bestparam[14],Bestparam[14]*0.2)  #Partner change rate in the very low group 0.04-0.5/year Nichols et al. 2016
 j1<-c(rnorm(1,Bestparam[15], Bestparam[15]*0.2),rnorm(1,Bestparam[16], Bestparam[16]*0.2),rnorm(1,Bestparam[17], Bestparam[17]*0.2),rnorm(1,Bestparam[18], Bestparam[18]*0.2))
  nvh<-j1[1]    #Proportion of the total population in each group 5-15% Nichols et al. 2016
  nh<-j1[2]      # previo 0.4---30-50% Nichols et al. 2016
  nl<-j1[3]      # previo 0.3---10-35% Nichols et al. 2016
  nvl<-j1[4]    # previo 0.1---4-46% # previo 0.1---4-46%
  
  B<-rnorm(1,Bestparam[19], Bestparam[19]*0.02)  #per partnership transmissibility Nichols et al 2016.
  I12<-invbeta(Bestparam[20],Bestparam[20]*0.2) #1 month duration in stage 1 of HIV infection
  I23<-invbeta(Bestparam[21],Bestparam[21]*0.2) #1 month duration in stage 2 of HIV infection
  I34<-invbeta(Bestparam[22],Bestparam[22]*0.2) #1 month duration in stage 3 of HIV infection
  I45<-invbeta(Bestparam[23],Bestparam[23]*0.2) #3 month duration in stage 4 of HIV infection
  I55<-invbeta(Bestparam[25],Bestparam[25]*0.2)  #3 month duration in stage 5 of HIV infection
  I56<-invbeta(Bestparam[26],Bestparam[26]*0.2)  #3 month duration in stage 6 of HIV infection
  I67<-invbeta(Bestparam[27],Bestparam[27]*0.2)  #Chronic duration in stage 7 of HIV infection
  I78<-invbeta(Bestparam[28],Bestparam[28]*0.2) #Chronic duration in stage 9 of HIV infection
  I89<-invbeta(Bestparam[29],Bestparam[29]*0.2)  #Chronic duration in stage 10 of HIV infection
  PTr<-c(invbeta(Bestparam[30],Bestparam[30]*0.2),invbeta(Bestparam[31],Bestparam[31]*0.2),
         invbeta(Bestparam[32],Bestparam[32]*0.2)) #Nuñez et al AIDS 2018   


QP<-HIVSIMPREP(Age, NoSem, NumHSH, NumHSHVIH, 
                 ACD4, I8CD4, I7CD4, Rest, 
                 G, Woff=1-exp(-0.12/52), W=1-exp(-0.3/52), 
                 m, mAIDS, mVIH235, mVIH35, mTr, 
                 Cvh, Ch, Cl, Cvl, 
                 nvh, nh, nl, nvl, B,
                 I12, I23, I34, 
                 I45, I55, 
                 I56, I67, 
                 I78, I89, PTr, years, PropTR)

MATP[a,]<-QALYCostP(QP)

}

MATP
}
```

```{r}
ncores<-detectCores()
cl<-makeCluster(ncores, type="PSOCK")
clusterSetRNGStream(cl, iseed=1)
clusterExport(cl, c("MATP", "Bestparam", "DistEdad", "Age", "years", "NoSem", "RiskRed","WAIDS", "WHIV", "WM350", "WTREAT", "WSusceptible", "Treatcost", "AIDScost", "PrEPcost","QALYCostP", "invbeta", "QalyCalc", "HIVSIMPREP", "PSAPrep", "CostCalc", "Woff", "W", "rdirichlet", "invbeta"))

MAT1P3<-clusterCall(cl, fun=PSAPrep, repeats)
#MAT1<-PSAPrep(10)
#MAT2<-PSA(10)
stopCluster(cl)
x<-vector(length=2, mode="numeric")
for (i in 1:ncores){x<-rbind(x,MAT1P3[[i]])}
MAT2P3<-as.matrix(x[-1,])
MAT2P3<-cbind(MAT2P3, "PREP-LEN-Red_02")
save(MAT2P3, file="MAT2P3")
MAT2P3
```
```{r}
PSADATA1<-cbind(MAT2P3[,1:2], MAT2[,1:2])
PSADATA1<-apply(PSADATA1, 2, as.numeric)
colnames(PSADATA1)<-c("QalysP", "CostsP", "Qalys", "Costs")
PSADATA1<-as_tibble(PSADATA1)
PSADATA1<-PSADATA1%>%mutate(AQalys=QalysP-Qalys, 
                            ACosts=CostsP-Costs,   
                            ICERS=(ACosts)/(AQalys))
PSADATA1<-PSADATA1[complete.cases(PSADATA1),]
PSADATA1
```


```{r}
PSADATA<-bind_rows(as.data.frame(MAT2P3), as.data.frame(MAT2))
colnames(PSADATA)<-c("Qalys", "Costs", "PREP")
PSADATA<-as_tibble(PSADATA)
PSADATA<-PSADATA%>%filter(Qalys!="NaN" | Costs!="NaN")
PSADATA[,1:2]<-lapply(PSADATA[,1:2],as.numeric)
#PSADATA
for (i in 1:nrow(PSADATA)) {if(PSADATA$PREP[i]=="PREP") PSADATA$PREP[i]<-"PREP-TDF"}

g<-ggplot(PSADATA, aes(Qalys, Costs, color=PREP))+
  geom_point(alpha=0.8)+
  theme_classic()+
  #ylim(-1000000000,100000000000)+
  #xlim(-1000000000,100000000000)+
  geom_hline(yintercept =0)+
  geom_vline(xintercept =0)+
  #scale_x_log10()+
  #scale_y_log10()+
  ylab("Costs in 2018 €")+
  xlab("Qalys")+
  ggtitle("Cost-effectiveness plane")+
  theme(plot.title = element_text(hjust=0.5))
  
#tiff("CEA.tif", width=16, height=12, units="cm", res=300)
g
#dev.off
```

```{r}
PSADATA2<-PSADATA1%>%filter(ICERS !=-Inf & ICERS !=Inf)
g1<-ggplot(PSADATA2, aes(x=ICERS))+
  stat_ecdf(na.rm=TRUE, position="identity")+
  #geom_histogram()+
  theme_classic()
  
g1
```
# Distribution of the ICERs
```{r}
summary(PSADATA2$ICERS)
percentile<-ecdf(PSADATA2$ICERS)
percentile(33895.59)
percentile(0)
```

```{r}
AnalBCEA<-bcea(as.matrix(PSADATA2[,c(1,3)]), as.matrix(PSADATA2[,c(2,4)]), ref=1, interventions=c("PrEP", "No-PrEP"), kmax=33895.59)
```
```{r}
ceplane.plot(AnalBCEA, graph="ggplot2")
```
```{r}
ceac.plot(AnalBCEA, graph="ggplot2")
```
